### ISSUE TITLE
[bug]: Re-Change Zip code data in Estimate Shipping Form at cart page error

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2751]
**Describe the bug**
I tried to change to zip code data when I submitted Estimate shipping method at cart page and error showing. 
`"Can't find field 'country' on object {
  "__typename": "ShippingCartAddress",
  "selected_shipping_method": {
    "__typename": "SelectedShippingMethod",
    "amount": {
      "__typename": "Money",
      "currency": "USD",
      "value": 0
    }
  }
}"`

**To reproduce**
1. Add any a product to cart
2. Go to cart page
3. Fill your country, state & zip code and submit that
3. Try to re-change zip code (remove, add new, edit, ...)
4. See error display (**develop** mode will show full screen & **production** mode show on console tab of browser)

**Expected behavior**

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/9253798/95010898-163dc380-0657-11eb-99a6-17d68cd09e24.png)

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Should be fixed by https://github.com/magento/pwa-studio/pull/2744 which was merged recently. Can you double check?

**Comment by huykon** [comment]
@sirugh I pulled the newest code from develop branch but still have that error

**Comment by sirugh** [comment]
Oh, that's because it was merged to the release/8.0 branch, which has not been backmerged yet!
